import {RFPercentage} from "react-native-responsive-fontsize";

export const FontSize = {
  font8: RFPercentage(1.17),
  font10: RFPercentage(1.47),
  font11: RFPercentage(1.6),
  font11p7: RFPercentage(1.7),
  font12: RFPercentage(1.76),
  font13: RFPercentage(1.9),
  fontEntry: RFPercentage(2.0),
  font14: RFPercentage(2.05),
  fontHeader: RFPercentage(2.1),
  fontTV: RFPercentage(2.2),
  font16: RFPercentage(2.35),
  font20: RFPercentage(2.4),
  fontNormal: RFPercentage(2.5),
  font18: RFPercentage(2.65),
  fontLargeExtra: RFPercentage(2.7),
  fontLargeExtra20: RFPercentage(2.9),
  fontLarge: RFPercentage(3.0),
  fontLargePlus: RFPercentage(3.125),
  fontXLarge: RFPercentage(3.5),
  fontXXLarge: RFPercentage(4.0),
  fontXXXLarge: RFPercentage(4.5),
  font36: RFPercentage(5.3),
  font48: RFPercentage(6.17),
};